name: Generate Snake Animation

on:
  schedule:
    # Roda a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions: # <--- Adicionado o bloco de permissões
  contents: write # <--- Permissão de escrita para o token do GitHub

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # Seu nome de usuário do GitHub
          github_user_name: Ailer20 
          
          # Onde o GIF será salvo (no seu repositório)
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
            
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          
      - name: Push new files
        uses: actions/upload-artifact@v4
        with:
          name: github-snake-animation
          path: dist/
